### ISSUE TITLE
TTK module failing

### ISSUE THREAD

**Issue by JochenJankowai** [inviwo/modules#152]
I have followed the instructions given in the readme.md in the TTK module (installed boost 1.70) but CMake fails with the following error:
![image](https://user-images.githubusercontent.com/2997626/111122705-aec56180-856e-11eb-8ca2-2313f5554e0b.png)

**Comment by ResearchDaniel** [comment]
Looks like you need to add boost to your PATH, or CMAKE_MODULE_PATH, for cmake to find it.
Perhpas this should be clarified in the instructions

**Comment by ResearchDaniel** [comment]
Hmm, it does say that it finds version 1.70.0...

**Comment by JochenJankowai** [comment]
It says to set `BOOST_INCLUDE_DIR` in the instructions which I did. And as you said, it finds the boost installation, just not the target it is looking for.

**Comment by JochenJankowai** [comment]
I know that @alab0329 had the same problem and has yet to get it to run.

**Comment by ResearchDaniel** [comment]
Perhaps Boost::All is not required and would identifying the individual necessary components would resolve the issue

**Comment by JochenJankowai** [comment]
I'll check out how Julien does it.

**Comment by JochenJankowai** [comment]
See #153
