### ISSUE TITLE
VTK as submodule

### ISSUE THREAD

**Issue by JochenJankowai** [inviwo/modules#154]
This is meant more as a discussion that an issue so feel free to just contribute.

Why do we not have VTK as submodule for the VTK module? I understand that it is a huge dependency. This may be heavy on the CI pipeline but:
1. The VTK module is not enabled as of now anyway
2. There's an option to cache files in-between builds so unless we update VTK, there is no need to compile it with every CI run.

As for the user, there's a bit of extra disk space needed but I suppose that shouldn't matter anymore nowadays. If the module is not enabled the binaries are not build and if the module is enabled, the user needs the disk space either way.

**Comment by petersteneteg** [comment]
We really don't want to add any more submodules. The plan is to removal the ones we have rather, and use a external package manager like for example vcpkg. There are many reasons for this, which I can expand of if needed. I would recommend you look into using vcpkg in you local setup to manage dependencies.
