### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by imanolooo** [inviwo/modules#168]
Hi,
I'm compiling inviwo with this extra module enabled and I'm having three compilation errors on dicomdirtypes.h.

I'm trying to compile on a fresh ubuntu instalation using CLion IDE.

The affected lines are from 178 to 187:
`template <class Elem, class Traits>
std::basic_ostream<Elem, Traits>& operator<<(std::basic_ostream<Elem, Traits>& ss,
                                             const dicomdir::Image& image) {
    ss << "[ DICOM Image" ss << "\n  Path:         " << image.path
       << "\n  Orientation: " << image.orientationPatient
       << "\n  Position:    " << image.positionPatient
       << "\n  Thickness:   " << image.sliceThickness << "\n  z pos:       " << image.zPos
       << "\n  Window (center, width): " << image.windowCenter << ", " << image.windowWidth << " ]";
    return ss;
}`

and the errors:
Line 181: Expected ';' after expression
Line 182: No member named 'orientationPatient' in 'inviwo::dicomdir::Image'
Line 183: No member named 'positionPatient' in 'inviwo::dicomdir::Image'

All seems logic to me. So, is there a bug, or how should I solve that?
Thanks!
Imanol

**Comment by martinfalk** [comment]
That appears to be a problem in the code. Most likely that templated function was not compiled before. Feel free to create a pull request with a fix.

**Comment by imanolooo** [comment]
I tried to create a pull request. But, first I need to publish my branch, isn't it? Github desktop says that I don't have permissions to do it...

**Comment by ResearchDaniel** [comment]
> I tried to create a pull request. But, first I need to publish my branch, isn't it? Github desktop says that I don't have permissions to do it...

I have now added permissions so that you can create a PR

**Comment by petersteneteg** [comment]
HI
Just create a fork, push to a branch in your fork, and then you can create a PR.

**Comment by petersteneteg** [comment]
fixed in #173
