### ISSUE TITLE
CMake: Not all TTK target are put into ext/ttk folder

### ISSUE THREAD

**Issue by r-englund** [inviwo/modules#62]
https://github.com/inviwo/modules/blob/8c5fd75a2973d7bca680ba7ce602af2c6f8fd9c0/topovis/topologytoolkit/ext/ttk/CMakeLists.txt#L37-L46

**Comment by r-englund** [comment]
Should probably change https://github.com/inviwo/modules/blob/8c5fd75a2973d7bca680ba7ce602af2c6f8fd9c0/topovis/topologytoolkit/ext/ttk/CMakeLists.txt#L37-L46  to 
```cmake
ivw_get_targets_in_dir_recursive(ttk_targets ${CMAKE_CURRENT_LIST_DIR}/ttk)
foreach(target ${ttk_targets})
    ivw_folder(${target} "ext/ttk")
endforeach()
```

**Comment by petersteneteg** [comment]
no point having TTK_BUILD_VTK_WRAPPERS enabled in inviwo...

**Comment by r-englund** [comment]
> 
> 
> no point having TTK_BUILD_VTK_WRAPPERS enabled in inviwo...

But it is still possible to enable it, and if so I think we should move the projects into the ext/ttk folder
