### ISSUE TITLE
GDCM / SourceForge git repo seems to very unstable

### ISSUE THREAD

**Issue by r-englund** [inviwo/modules#66]
The git repo for the submodule in the DICOM module (https://git.code.sf.net/p/gdcm/gdcm/) is hosted by SourceForge. 
It seems that its availability is not that reliable, it is currently resulting in `503 Service Unavailable`. 
This happened a few weeks ago as well, should we make a fork out of it? 
![image](https://user-images.githubusercontent.com/534670/66758452-96937380-ee9e-11e9-9c1f-8d50bb8d1946.png)
(@petersteneteg @martinfalk )

**Comment by martinfalk** [comment]
might be a good idea.
