### ISSUE TITLE
TopologicalSimplification will not allways process with new data 

### ISSUE THREAD

**Issue by r-englund** [inviwo/modules#89]
If the processor gets new data (or properties are modified) while the background thread is processing no new calculation will be started since both the `if` statement and the `else if` statements are false. 
To work around this one has to invalidate the output of the processor to start the calculation on the new data. 
A fix for this would be to change the `else if` to a plain `else`

https://github.com/inviwo/modules/blob/102728507723b172284d9da2832859740c22663c/topovis/topologytoolkit/src/processors/topologicalsimplification.cpp#L84-L106

**Comment by petersteneteg** [comment]
but that would also potentially spawn lots and lots of background jobs when interacting...
